import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import type {ClientRequest,IncomingMessage} from 'node:http';
import type {RequestOptions} from 'node:https';
import type {DetailedPeerCertificate} from 'node:tls';
import {readFile,mkdtemp,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {attachmentURL,publicAddress,pinnedOptions,downloadAttachment,normalizeAttachment,RAW_CAP} from '../server/mcp/attachment-download.js';
import {LocalBackend} from '../scripts/mcp-local-backend.js';
for(const ip of ['0.0.0.0','10.0.0.1','100.64.0.1','127.0.0.1','169.254.169.254','172.16.0.1','192.168.0.1','192.0.0.1','192.0.2.1','198.18.0.1','198.51.100.1','203.0.113.1','224.0.0.1','240.0.0.1','255.255.255.255','::','::1','::ffff:127.0.0.1','::ffff:8.8.8.8','64:ff9b::a00:1','fe80::1','fc00::1','ff02::1','2001:db8::1','2001::1','2002:7f00:1::'])assert(!publicAddress(ip),ip);
for(const ip of ['8.8.8.8','1.1.1.1','2606:4700:4700::1111'])assert(publicAddress(ip),ip);
for(const u of ['http://example.com/a','file:///a','https://user:pass@example.com/a','https://example.com:444/a','https://example.com/a#fragment','https://localhost/a','https://127.1/a','https://0x7f000001/a','https://2130706433/a','https://[::1]/a','https://example.com/\\evil'])assert.throws(()=>attachmentURL(u));
const options=pinnedOptions(attachmentURL('https://origin.example/photo?token=secret'),{address:'8.8.8.8',family:4},new AbortController().signal);
assert.equal(options.hostname,'8.8.8.8');assert.equal(options.servername,'origin.example');assert.equal(options.rejectUnauthorized,true);assert.equal(options.maxHeaderSize,8192);assert.equal(options.agent,false);
assert.deepEqual(Object.keys(options.headers||{}).sort(),['Accept','Accept-Encoding','Host'].sort());
assert.equal(options.checkServerIdentity!('8.8.8.8',{subjectaltname:'DNS:origin.example',subject:{CN:'origin.example'}} as unknown as DetailedPeerCertificate),undefined);
assert(options.checkServerIdentity!('origin.example',{subjectaltname:'DNS:wrong.example',subject:{CN:'wrong.example'}} as unknown as DetailedPeerCertificate));
let sends=0;const recorded:RequestOptions[]=[];
function fake(replies:Array<{status?:number;headers?:Record<string,string>;chunks?:Buffer[];hang?:boolean}>){
 return (opts:RequestOptions,callback:(r:IncomingMessage)=>void)=>{sends++;recorded.push(opts);const req=new EventEmitter() as ClientRequest;
 req.destroy=()=>{queueMicrotask(()=>req.emit('error',new Error('aborted')));return req;};
 opts.signal?.addEventListener('abort',()=>req.destroy(),{once:true});
 req.end=(()=>{queueMicrotask(()=>{const item=replies.shift()!;if(item.hang)return;const stream=new PassThrough() as unknown as IncomingMessage;Object.assign(stream,{statusCode:item.status||200,headers:item.headers||{}});callback(stream);for(const chunk of item.chunks||[Buffer.from('bytes')]){if(stream.destroyed)break;(stream as unknown as PassThrough).write(chunk);}if(!stream.destroyed)(stream as unknown as PassThrough).end();});return req;}) as ClientRequest['end'];return req;
 };
}
const dns=async()=>[{address:'8.8.8.8',family:4 as const}];
assert.equal((await downloadAttachment('https://origin.example/a',{resolve:dns,request:fake([{}])})).toString(),'bytes');
const before=sends;
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:async()=>[{address:'8.8.8.8',family:4},{address:'127.0.0.1',family:4}],request:fake([{}])}));assert.equal(sends,before);
let resolutions=0;await downloadAttachment('https://origin.example/a',{resolve:async()=>{resolutions++;return dns();},request:fake([{status:302,headers:{location:'https://second.example/a'}},{}])});assert.equal(resolutions,2);assert.equal(recorded.at(-1)?.hostname,'8.8.8.8');assert.equal(recorded.at(-1)?.servername,'second.example');
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:dns,request:fake([{status:302,headers:{location:'https://127.0.0.1/a'}}])}));
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:dns,request:fake(Array.from({length:4},()=>({status:302,headers:{location:'/again'}})))}));
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:dns,request:fake([{headers:{'content-encoding':'gzip'}}])}));
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:dns,request:fake([{headers:{'content-length':String(RAW_CAP+1)}}])}));
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:dns,request:fake([{chunks:[Buffer.alloc(RAW_CAP),Buffer.alloc(1)]}])}));
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:dns,request:fake([{hang:true}]),timeoutMs:25}));
await assert.rejects(downloadAttachment('https://origin.example/a',{resolve:(_h,s)=>new Promise((_r,reject)=>s.addEventListener('abort',()=>reject(new Error('DNS timeout')),{once:true})),request:fake([{}]),timeoutMs:25}));
console.log('PASS SSRF policy: reserved IPv4/IPv6, literal obfuscation, mixed DNS, numeric connection pinning, original TLS identity, redirects, no secret headers, compression, streaming cap and wall timeout');
for(const name of ['qa-photo.jpg','qa-transparent.png','qa-exif.jpg','qa-oriented.jpg']){const normalized=await normalizeAttachment(await readFile('tests/fixtures/'+name));assert(normalized.bytes.length<=1048576);assert(Math.max(normalized.width,normalized.height)<=1920);const m=await sharp(normalized.bytes).metadata();assert.equal(m.format,'webp');assert(!m.exif&&!m.xmp&&!m.iptc);}
const webp=await sharp(await readFile('tests/fixtures/qa-photo.jpg')).webp().toBuffer();assert.equal((await normalizeAttachment(webp)).source_format,'webp');
await assert.rejects(normalizeAttachment(await readFile('tests/fixtures/qa-corrupt.jpg')));await assert.rejects(normalizeAttachment(Buffer.alloc(RAW_CAP+1)));
console.log('PASS image safety: actual JPEG/PNG/WebP decode, orientation handling, EXIF removal, no upscale, WebP normalized ceiling; HEIC PENDING');
await mkdir('output',{recursive:true});const root=await mkdtemp(resolve('output','mcp-attachment-budget-')),backend=await LocalBackend.open(root,'http://localhost:1'),actor={id:'budget-test',actor:randomUUID(),write:true};await backend.register(actor);
const budget=(role:'service_role'|'authenticated',id:string)=>backend.db.transaction(async tx=>{await tx.exec('set local role '+role);return tx.query('select public.mcp_attachment_download_budget($1)',[id]);});
for(let i=0;i<10;i++)await budget('service_role',actor.id);
await assert.rejects(budget('service_role',actor.id),/RATE_LIMITED/);
await assert.rejects(budget('authenticated',actor.id));
await assert.rejects(budget('service_role','unmapped'),/FORBIDDEN/);
await backend.db.close();console.log('PASS SQL download budget: durable 10/hour limit, actor mapping and grants; local PGlite only');
