import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import sharp from 'sharp';
import {LocalBackend} from '../scripts/mcp-local-backend.js';
import {RoadTagService,hash} from '../server/roadtag/service.js';
import {attachmentWrite} from '../server/mcp/attachment-write.js';
const backend=await LocalBackend.open(await mkdtemp(join(tmpdir(),'roadtag-bridge-')),'https://preview.example.com'),p={id:'writer',actor:randomUUID(),write:true},other={id:'other',actor:randomUUID(),write:true};
await backend.register(p);await backend.register(other);
const service=new RoadTagService(backend,'https://preview.example.com','s'.repeat(32)),image=await sharp({create:{width:80,height:40,channels:3,background:'red'}}).png().toBuffer();
let downloads=0;const download=async()=>{downloads++;return image;};
const input=(op=randomUUID())=>({operation_id:op,city_id:'TW-KEE',district:'仁愛區',lat:25.13,lng:121.74,title:'  Bridge QA  ',category:'other',wheelchair_access:'passable',confirmed:true,photo_file:{download_url:'https://example.com/private?secret=value',file_id:'private-id',mime_type:'image/png'}});
const first=input(),result=await attachmentWrite(service,'create_report',first,p,download);assert.equal(result.created,true);assert.equal(downloads,1);
const replay=await attachmentWrite(service,'create_report',{...first,title:'Bridge QA',photo_file:{...first.photo_file,download_url:'http://127.0.0.1/expired'}},p,async()=>{throw Error('refetch forbidden');});assert.equal(replay.replayed,true);assert.equal(replay.report_id,result.report_id);
await assert.rejects(attachmentWrite(service,'create_report',{...first,photo_file:{...first.photo_file,file_id:'different'}},p,download),/IDEMPOTENCY_CONFLICT/);
await assert.rejects(attachmentWrite(service,'create_report',{...first,title:'different'},p,download),/IDEMPOTENCY_CONFLICT/);
await assert.rejects(attachmentWrite(service,'create_report',first,other,download),/FORBIDDEN/);
await assert.rejects(attachmentWrite(service,'create_report',{...first,confirmed:false},p,download),/CONFIRMATION_REQUIRED/);
const obs={operation_id:randomUUID(),report_id:result.report_id,message:'Staging observation',suggested_status:'resolved',confirmed:true,photo_file:first.photo_file};
const added=await attachmentWrite(service,'add_observation',obs,p,download);assert.equal(added.added,true);
const obsReplay=await attachmentWrite(service,'add_observation',{...obs,photo_file:{...obs.photo_file,download_url:'expired'}},p,async()=>{throw Error('refetch forbidden');});assert.equal(obsReplay.observation_id,added.observation_id);
assert.equal((await backend.feed({id:String(result.report_id)}))[0].status,'open');
await backend.db.exec("update private.rate_limits set last_at=now()-interval '1 hour'");
const race=input();const winners=await Promise.allSettled([attachmentWrite(service,'create_report',race,p,download),attachmentWrite(service,'create_report',race,p,download)]);
assert(winners.some(x=>x.status==='fulfilled'),winners.map(x=>x.status==='rejected'?String(x.reason):'PASS').join(','));for(const x of winners)if(x.status==='rejected')assert.match(String(x.reason),/RATE_LIMITED/);
assert.equal((await attachmentWrite(service,'create_report',race,p,async()=>{throw Error('no refetch');})).replayed,true);
await backend.db.exec("update private.rate_limits set last_at=now()-interval '1 hour'");
const lost=input(),rpc=backend.rpc.bind(backend);let injected=false;
backend.rpc=async(name,args)=>{const r=await rpc(name,args);if(name==='mcp_write'&&args.op===lost.operation_id&&!injected){injected=true;throw Error('lost acknowledgement');}return r;};
await assert.rejects(attachmentWrite(service,'create_report',lost,p,download),/lost acknowledgement/);
assert.equal((await attachmentWrite(service,'create_report',lost,p,async()=>{throw Error('no refetch');})).replayed,true);
backend.rpc=rpc;
await backend.db.exec("update private.rate_limits set last_at=now()-interval '1 hour'");
const incomplete=input();let failPut=true;const put=backend.put.bind(backend);
backend.put=async(...args)=>{if(failPut){failPut=false;throw Error('upload failed');}return put(...args);};
await assert.rejects(attachmentWrite(service,'create_report',incomplete,p,download),/upload failed/);
const different=await sharp(image).negate().png().toBuffer();
await assert.rejects(attachmentWrite(service,'create_report',incomplete,p,async()=>different),/IDEMPOTENCY_CONFLICT/);
backend.put=put;
const sql=await backend.db.query<{total:number;file_hash:string;business:unknown}>('select count(*) over()::int as total,file_hash,business from private.mcp_attachment_ops');
assert(sql.rows.every(r=>r.file_hash===hash('private-id')));assert(!JSON.stringify(sql.rows).includes('private-id'));assert(!JSON.stringify(sql.rows).includes('secret=value'));
const counts=await backend.db.query<{objects:number;operations:number}>('select (select count(*)::int from storage.objects) as objects,(select count(*)::int from private.mcp_operations) as operations');assert.equal(counts.rows[0].objects,counts.rows[0].operations);
await backend.db.transaction(async tx=>{await tx.exec('set local role authenticated');await assert.rejects(tx.query('select * from private.mcp_attachment_ops'),/permission denied/);});
console.log('PASS attachment bridge: normalized payload/hash binding, replay before expired URL, digest conflict before overwrite, concurrent retry one object/write, lost acknowledgement original ID, observation status preserved and no sensitive fields');
const guard=input(),lease1=randomUUID(),lease2=randomUUID(),bind={p:p.id,op:guard.operation_id,tool_name:'create_report',data:{confirmed:true},file_hash:hash('guard-file'),lease:lease1};
assert.equal((await backend.rpc('mcp_attachment_begin',bind)).busy,false);
assert.equal((await backend.rpc('mcp_attachment_begin',{...bind,lease:lease2})).busy,true);
await assert.rejects(backend.rpc('mcp_attachment_digest',{p:p.id,op:guard.operation_id,lease:lease2,digest:hash('x')}),/FORBIDDEN/);
await backend.rpc('mcp_attachment_release',{p:p.id,op:guard.operation_id,lease:lease2});
assert.equal((await backend.rpc('mcp_attachment_begin',{...bind,lease:lease2})).busy,true);
await backend.db.query("update private.mcp_attachment_ops set lease_until=now()-interval '1 second' where operation=$1",[guard.operation_id]);
assert.equal((await backend.rpc('mcp_attachment_begin',{...bind,lease:lease2})).busy,false);
await assert.rejects(backend.rpc('mcp_attachment_digest',{p:p.id,op:guard.operation_id,lease:lease1,digest:hash('x')}),/FORBIDDEN/);
await backend.rpc('mcp_attachment_digest',{p:p.id,op:guard.operation_id,lease:lease2,digest:hash('x')});
await assert.rejects(backend.rpc('mcp_attachment_digest',{p:p.id,op:guard.operation_id,lease:lease2,digest:hash('y')}),/IDEMPOTENCY_CONFLICT/);
await backend.rpc('mcp_attachment_release',{p:p.id,op:guard.operation_id,lease:lease1});
assert.equal((await backend.rpc('mcp_attachment_begin',{...bind,lease:lease1})).busy,true);
await backend.db.transaction(async tx=>{await tx.exec('set local role authenticated');await assert.rejects(tx.query('select public.mcp_attachment_release($1,$2,$3)',[p.id,guard.operation_id,lease2]),/permission denied/);});
assert.equal((await backend.db.query<{n:number}>('select count(*)::int as n from private.mcp_actor_sessions')).rows[0].n,0);
console.log('PASS ingestion lease fencing, stale release rejection, expired invocation takeover, service-only RPC grants and unchanged Auth lock state');

await backend.db.close();
